// vm.rs
// CruxLang Virtual Machine: Executes bytecode instructions generated by the compiler.
// Manages stack, environments, modules, and program output.

use crate::bytecode::Value;
use crate::bytecode::Instruction;
use std::collections::HashMap;

pub struct Module {
    pub functions: HashMap<String, fn(Vec<Value>) -> Result<Value, String>>,
}

pub struct VM {
    // === VM State ===
    // These fields are like the "memory" and "workspace" of the virtual machine:
    // - ip: Keeps track of which instruction we're on (like a bookmark)
    // - stack: Where we do our calculations (like scratch paper)
    // - call_stack: Remembers function calls (like a stack of recipe cards)
    // - env_stack: Keeps track of variables in different scopes (like nested boxes)
    // - output: Stores anything the program prints
    // - modules: Built-in or imported modules (like a toolbox)
    ip: usize,
    stack: Vec<Value>,
    instructions: Vec<(Instruction, usize)>, // now includes line numbers
    call_stack: Vec<(String, usize)>, // function name, line number
    env_stack: Vec<HashMap<String, Value>>, // stack of environments
    output: Vec<String>, // captured output
    modules: HashMap<String, Module>,
}

impl VM {
    pub fn new(instructions: Vec<(Instruction, usize)>) -> Self {
        let mut modules = HashMap::new();
        // Add a dummy 'math' module with 'sqrt' function
        let mut math_fns = HashMap::new();
        math_fns.insert("sqrt".to_string(), math_sqrt as fn(Vec<Value>) -> Result<Value, String>);
        math_fns.insert("range".to_string(), math_range as fn(Vec<Value>) -> Result<Value, String>);
        modules.insert("math".to_string(), Module { functions: math_fns });
        VM {
            ip: 0,
            stack: Vec::new(),
            instructions,
            call_stack: Vec::new(),
            env_stack: vec![HashMap::new()], // start with global env
            output: Vec::new(),
            modules,
        }
    }

    /// Get the output produced by the program.
    pub fn get_output(&self) -> String {
        self.output.join("\n")
    }

    // === Variable Lookup ===
    // This function searches through all the variable "boxes" (environments) from most recent to oldest.
    // If it finds the variable, it returns its value. If not, it returns Null.
    fn get_var(&self, name: &str) -> Value {
        for env in self.env_stack.iter().rev() {
            if let Some(val) = env.get(name) {
                return val.clone();
            }
        }
        Value::Null
    }

    fn set_var(&mut self, name: &str, val: Value) {
        for env in self.env_stack.iter_mut().rev() {
            if env.contains_key(name) {
                env.insert(name.to_string(), val);
                return;
            }
        }
        // If not found, set in the topmost (current) environment
        if let Some(env) = self.env_stack.last_mut() {
            env.insert(name.to_string(), val);
        }
    }

    pub fn run(&mut self) -> Result<(), String> {
        while self.ip < self.instructions.len() {
            let (instruction, line) = self.instructions[self.ip].clone();
            // --- DEBUG OUTPUT ---
            println!("[VM] ip: {} | instr: {:?} | stack: {:?}", self.ip, instruction, self.stack);
            println!("[VM] env_stack: {:?}", self.env_stack);
            // --- END DEBUG OUTPUT ---
            match instruction {
                Instruction::LoadNumber(n) => {
                    self.stack.push(Value::Number(n));
                }
                Instruction::LoadString(s) => {
                    self.stack.push(Value::String(s));
                }
                Instruction::LoadBool(b) => {
                    self.stack.push(Value::Bool(b));
                }
                Instruction::LoadVar(name) => {
                    let val = self.get_var(&name);
                    println!("[DEBUG] LoadVar: {} => {:?}", name, val);
                    self.stack.push(val);
                    println!("[DEBUG] env_stack after LoadVar: {:?}", self.env_stack);
                }
                Instruction::StoreVar(name) => {
                    let val = self.stack.pop().ok_or("Stack underflow on StoreVar")?;
                    println!("[DEBUG] StoreVar: {} <= {:?}", name, val);
                    self.set_var(&name, val);
                    println!("[DEBUG] env_stack after StoreVar: {:?}", self.env_stack);
                }
                Instruction::Emit => {
                    if let Some(val) = self.stack.pop() {
                        self.output.push(val.to_string());
                    } else {
                        return self.error("Stack underflow on emit".to_string(), line);
                    }
                }
                Instruction::ConcatStrings(count) => {
                    if self.stack.len() < count {
                        return self.error(format!("Stack underflow on ConcatStrings({})", count), line);
                    }
                    let mut strings = Vec::with_capacity(count);
                    for _ in 0..count {
                        if let Some(val) = self.stack.pop() {
                            strings.push(val.to_string());
                        } else {
                            return self.error("Stack underflow on ConcatStrings".to_string(), line);
                        }
                    }
                    strings.reverse(); // Restore original order
                    let result = strings.join("");
                    self.stack.push(Value::String(result));
                }
                Instruction::Pop => {
                    self.stack.pop();
                }
                Instruction::Return => {
                    self.call_stack.pop();
                    self.env_stack.pop(); // pop local env
                    return Ok(());
                }
                Instruction::BinaryOp(op) => {
                    let right = self.stack.pop().ok_or("Missing right operand")?;
                    let left = self.stack.pop().ok_or("Missing left operand")?;

                    let result = match (left, right) {
                        (Value::Number(l), Value::Number(r)) => match op.as_str() {
                            "+" => Value::Number(l + r),
                            "-" => Value::Number(l - r),
                            "*" => Value::Number(l * r),
                            "/" => Value::Number(l / r),
                            "==" => Value::Bool(l == r),
                            "!=" => Value::Bool(l != r),
                            "<" => Value::Bool(l < r),
                            "<=" => Value::Bool(l <= r),
                            ">" => Value::Bool(l > r),
                            ">=" => Value::Bool(l >= r),
                            _ => return self.error(format!("Unknown binary operator {}", op), line),
                        },
                        (Value::Bool(l), Value::Bool(r)) => match op.as_str() {
                            "and" => Value::Bool(l && r),
                            "or" => Value::Bool(l || r),
                            _ => return self.error(format!("Unknown boolean operator {}", op), line),
                        },
                        _ => return self.error("Operands must be numbers or booleans".to_string(), line),
                    };
                    self.stack.push(result);
                    println!("[DEBUG] stack after BinaryOp: {:?}", self.stack);
                }
                Instruction::Not => {
                    let value = self.stack.pop().ok_or("Missing operand for Not")?;
                    let result = match value {
                        Value::Bool(b) => Value::Bool(!b),
                        _ => return self.error("Operand for 'not' must be boolean".to_string(), line),
                    };
                    self.stack.push(result);
                }
                Instruction::CallFunc(_name, arg_count) => {
                    let args: Vec<Value> = self.stack.drain(self.stack.len() - arg_count..).collect();
                    let func_val = self.stack.pop().ok_or("Missing function value")?;
                    println!("[DEBUG] CallFunc: about to call {:?} with args {:?}", func_val, args);
                    match func_val {
                        Value::Function { name: func_name, params, body } => {
                            if params.len() != arg_count {
                                return self.error(
                                    format!("Expected {} arguments but got {}", params.len(), arg_count),
                                    line,
                                );
                            }

                            let mut local_vm = VM::new(body.clone());
                            local_vm.env_stack = self.env_stack.clone();
                            local_vm.env_stack.push(HashMap::new());
                            if let Some(local_env) = local_vm.env_stack.last_mut() {
                                for (param, arg) in params.iter().zip(args) {
                                    local_env.insert(param.clone(), arg);
                                }
                            }
                            local_vm.call_stack = self.call_stack.clone();
                            local_vm.call_stack.push((func_name.clone(), line));

                            match local_vm.run() {
                                Ok(_) => {
                                    if let Some(val) = local_vm.stack.pop() {
                                        self.stack.push(val);
                                    } else {
                                        self.stack.push(Value::Null);
                                    }
                                }
                                Err(e) => return Err(e),
                            }
                        }
                        Value::NativeFunc(f) => {
                            match f(args) {
                                Ok(val) => self.stack.push(val),
                                Err(e) => return self.error(e, line),
                            }
                        }
                        _ => return self.error("Trying to call a non-function value".to_string(), line),
                    }
                    println!("[DEBUG] stack after CallFunc: {:?}", self.stack);
                }
                Instruction::MakeFunc { name, params, chunk } => {
                    // Convert chunk to Vec<(Instruction, usize)>
                    let body: Vec<(Instruction, usize)> = chunk.instructions.iter().cloned().zip(chunk.lines.iter().cloned()).collect();
                    self.stack.push(Value::Function {
                        name: name.clone(),
                        params: params.clone(),
                        body,
                    });
                }
                Instruction::JumpIfFalse(target) => {
                    let cond = self.stack.pop().ok_or("Missing condition for JumpIfFalse")?;
                    if let Value::Bool(false) = cond {
                        self.ip = target;
                        continue;
                    }
                }
                Instruction::Jump(target) => {
                    self.ip = target;
                    continue;
                }
                Instruction::MakeArray(n) => {
                    if self.stack.len() < n {
                        return self.error(format!("Stack underflow on MakeArray({})", n), line);
                    }
                    let mut elements = Vec::with_capacity(n);
                    for _ in 0..n {
                        elements.push(self.stack.pop().unwrap());
                    }
                    elements.reverse(); // so the first element is at the bottom
                    self.stack.push(Value::Array(elements));
                }
                Instruction::IndexAccess => {
                    let index_val = self.stack.pop().ok_or("Stack underflow on IndexAccess (index)")?;
                    let array_val = self.stack.pop().ok_or("Stack underflow on IndexAccess (array)")?;
                    match (array_val, index_val) {
                        (Value::Array(arr), Value::Number(n)) => {
                            let idx = n as usize;
                            if idx < arr.len() {
                                self.stack.push(arr[idx].clone());
                            } else {
                                return self.error(format!("Array index {} out of bounds (len={})", idx, arr.len()), line);
                            }
                        }
                        _ => {
                            return self.error("Indexing requires an array and a number index".to_string(), line);
                        }
                    }
                }
                Instruction::GetIterator => {
                    let iterable = self.stack.pop().ok_or("Stack underflow on GetIterator")?;
                    match iterable {
                        Value::Array(elements) => {
                            // Create a simple iterator (just store the array and current index)
                            self.stack.push(Value::Iterator {
                                elements,
                                current_index: 0,
                            });
                        }
                        _ => return self.error("GetIterator requires an array".to_string(), line),
                    }
                }
                Instruction::HasNext => {
                    let iterator = self.stack.pop().ok_or("Stack underflow on HasNext")?;
                    match iterator {
                        Value::Iterator { elements, current_index } => {
                            let has_next = current_index < elements.len();
                            // Push the iterator back and the boolean result
                            self.stack.push(Value::Iterator { elements, current_index });
                            self.stack.push(Value::Bool(has_next));
                        }
                        _ => return self.error("HasNext requires an iterator".to_string(), line),
                    }
                }
                Instruction::GetNext => {
                    let iterator = self.stack.pop().ok_or("Stack underflow on GetNext")?;
                    match iterator {
                        Value::Iterator { elements, current_index } => {
                            if current_index >= elements.len() {
                                return self.error("Iterator has no more elements".to_string(), line);
                            }
                            let element = elements[current_index].clone();
                            let next_index = current_index + 1;
                            // Push the updated iterator and the element
                            self.stack.push(Value::Iterator { elements, current_index: next_index });
                            self.stack.push(element);
                        }
                        _ => return self.error("GetNext requires an iterator".to_string(), line),
                    }
                }
                Instruction::Break(target) => {
                    self.ip = target;
                    continue;
                }
                Instruction::MakeClass { name, methods } => {
                    let mut method_map = HashMap::new();
                    for (mname, params, chunk) in methods {
                        let body: Vec<(Instruction, usize)> = chunk.instructions.iter().cloned().zip(chunk.lines.iter().cloned()).collect();
                        method_map.insert(mname, (params, body));
                    }
                    self.stack.push(Value::Class { name, methods: method_map });
                }
                Instruction::MakeObject { class, field_count } => {
                    let mut fields = HashMap::new();
                    for _ in 0..field_count {
                        let name_val = self.stack.pop().unwrap_or(Value::Null);
                        let value = self.stack.pop().unwrap_or(Value::Null);
                        let name = match name_val {
                            Value::String(s) => s,
                            _ => "field".to_string(),
                        };
                        fields.insert(name, value);
                    }
                    self.stack.push(Value::Object { class, fields });
                }
                Instruction::GetField(field) => {
                    let obj = self.stack.pop().ok_or("Stack underflow on GetField")?;
                    match obj {
                        Value::Object { fields, .. } => {
                            let val = fields.get(&field).cloned().unwrap_or(Value::Null);
                            self.stack.push(val);
                        }
                        _ => return self.error("GetField requires an object".to_string(), line),
                    }
                }
                Instruction::ModuleCall { module, func, argc } => {
                    let mut args = Vec::with_capacity(argc);
                    for _ in 0..argc {
                        args.push(self.stack.pop().ok_or("Missing argument for module call")?);
                    }
                    args.reverse();
                    if let Some(module_obj) = self.modules.get(&module) {
                        if let Some(f) = module_obj.functions.get(&func) {
                            match f(args) {
                                Ok(val) => self.stack.push(val),
                                Err(e) => return self.error(e, line),
                            }
                        } else {
                            return self.error(format!("Function '{}' not found in module '{}'", func, module), line);
                        }
                    } else {
                        return self.error(format!("Module '{}' not found", module), line);
                    }
                }
                Instruction::ModuleImport { module: _, .. } => {
                    // For now, modules are preloaded
                }
                Instruction::CallMethod(method, arg_count) => {
                    let mut args = Vec::with_capacity(arg_count);
                    for _ in 0..arg_count {
                        args.push(self.stack.pop().ok_or("Missing argument for method call")?);
                    }
                    args.reverse();
                    let obj = self.stack.pop().ok_or("Missing object for method call")?;
                    match obj {
                        Value::Object { class, fields } => {
                            // Find class definition
                            let class_val = self.get_var(&class);
                            match class_val {
                                Value::Class { methods, .. } => {
                                    if let Some((params, body)) = methods.get(&method) {
                                        if params.len() != args.len() {
                                            return self.error(format!("Expected {} arguments but got {}", params.len(), args.len()), line);
                                        }
                                        let mut local_vm = VM::new(body.clone());
                                        // Inherit environment
                                        local_vm.env_stack = self.env_stack.clone();
                                        // New environment for method call
                                        let mut method_env = HashMap::new();
                                        // Bind self
                                        method_env.insert("self".to_string(), Value::Object { class: class.clone(), fields: fields.clone() });
                                        // Bind arguments
                                        for (param, arg) in params.iter().zip(args) {
                                            method_env.insert(param.clone(), arg);
                                        }
                                        local_vm.env_stack.push(method_env);
                                        local_vm.call_stack = self.call_stack.clone();
                                        local_vm.call_stack.push((method.clone(), line));
                                        match local_vm.run() {
                                            Ok(_) => {
                                                if let Some(val) = local_vm.stack.pop() {
                                                    self.stack.push(val);
                                                } else {
                                                    self.stack.push(Value::Null);
                                                }
                                            }
                                            Err(e) => return Err(e),
                                        }
                                    } else {
                                        return self.error(format!("Method '{}' not found on class '{}'", method, class), line);
                                    }
                                }
                                _ => return self.error(format!("Class '{}' not found for method call", class), line),
                            }
                        }
                        _ => return self.error("Trying to call a method on a non-object value".to_string(), line),
                    }
                }
                _ => return self.error(format!("Unknown instruction {:?}", instruction), line),
            }

            self.ip += 1;
        }

        Ok(())
    }

    fn error(&self, message: String, line: usize) -> Result<(), String> {
        let mut trace = format!("Runtime Error on line {}: {}\n", line, message);
        if !self.call_stack.is_empty() {
            trace += "Stack trace:\n";
            for (func, l) in self.call_stack.iter().rev() {
                trace += &format!("  at {} (line {})\n", func, l);
            }
        }
        Err(trace)
    }
}

fn math_sqrt(args: Vec<Value>) -> Result<Value, String> {
    if args.len() != 1 {
        return Err("sqrt expects 1 argument".to_string());
    }
    match &args[0] {
        Value::Number(n) => Ok(Value::Number(n.sqrt())),
        _ => Err("sqrt expects a number".to_string()),
    }
}

fn math_range(args: Vec<Value>) -> Result<Value, String> {
    if args.len() != 2 {
        return Err("range expects 2 arguments (start, end)".to_string());
    }
    
    let start = match &args[0] {
        Value::Number(n) => *n as i32,
        _ => return Err("range start must be a number".to_string()),
    };
    
    let end = match &args[1] {
        Value::Number(n) => *n as i32,
        _ => return Err("range end must be a number".to_string()),
    };
    
    let mut elements = Vec::new();
    for i in start..end {
        elements.push(Value::Number(i as f64));
    }
    
    Ok(Value::Array(elements))
}
